/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Date of configure */
#define CONFIGURE_DATE "Mon May 16 18:27:03 CEST 2011"

/* Name of package */
#define PACKAGE "systemc-ams"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* SVN Revision */
#define REVISION "$Revision: 1199 $"

/* Version number of package */
#define VERSION "1.0Beta2"
